### ISSUE TITLE
[UI] Some part of the description text are out of screen

### ISSUE THREAD

**Issue by Crescendo-BLYAT** [Catfriend1/syncthing-android#1177] opened 2024-11-12 15:04 UTC
### Description of the issue
![Screenshot_20241112_215158_Syncthing-Fork](https://github.com/user-attachments/assets/d94fcd23-5fd7-4581-b1d0-57e4ff259657)

### Version Information
- App Version: 1.27.9.0
- Syncthing Version: v1.27.9
- Android Version: Android 13 
- Device manufacturer: Samsung 
- Device model: SM-G780G 

It's not a bug, it's just an UI misalignment.

**Comment by Crescendo-BLYAT** [comment] 2024-11-12 15:05
If untrusted, enter encryption pas [text out of bound]

**Comment by Catfriend1** [comment] 2024-11-15 22:51
I know, made this to support receiveEncrypted. Someone with layout skills may PR to improve it. Does at least its job for the moment.

**Comment by Catfriend1** [comment] 2024-12-10 13:03
Duplicate of https://github.com/Catfriend1/syncthing-android/issues/1012

**Closed by Catfriend1** 2024-12-10 13:03 UTC
Labels: pr-welcome
