### ISSUE TITLE
0.14.53.1/54.1 Hangs on 4.4.2 Kitkat

### ISSUE THREAD

**Issue by phuyuk** [Catfriend1/syncthing-android#139] opened 2018-12-16 07:58 UTC
4.4.2 Kitkat
ST Versions: 0.14.53.1 & 0.14.54.1

After upgrading to either 0.14.53.1 or 0.14.54.1, my Kitkat phone stuck forever at "Syncthing is starting", along with hot battery.

Strictly speaking, the wrapper isn't hanging, since I'm still able to, for example, open settings. 'Start directly into web GUI' results in similarly endless "Waiting for GUI".

This occurs even after fresh (re)install, with default settings; after generating keys, stuck at same message and high CPU (> 10%).

Incrementally upgrading from old versions - even with default settings and no devices/folders - also fails upon reaching 0.14.53.1.

Reverting to 0.14.52.2 or lower resolves the issue.

**Comment by Catfriend1** [comment] 2018-12-16 08:20
Duplicate of https://github.com/Catfriend1/syncthing-android/issues/137 .
Hi @phuyuk,
Can you please test if the apk from the linked issue solves the problem?
Kind regards

**Comment by phuyuk** [comment] 2018-12-16 08:38
0.14.54.2 debug seems to have resolved the issuee.

Thank you.

**Comment by Catfriend1** [comment] 2018-12-16 09:38
I'll make a release. Thanks for your feedback! :-)

**Closed** 2018-12-16 09:44 UTC
