### ISSUE TITLE
The progress indicator was not correct

### ISSUE THREAD

**Issue by gbsix** [Catfriend1/syncthing-android#966] opened 2023-02-19 02:58 UTC
### Description of the issue
Actually sync completed, but the number stuck there.

### Reproduction Steps
Ofen.

### Version Information
- App Version: 1.23.0.0
- Syncthing Version: v1.23.1
- Android Version: Harmony OS 3.0 
- Device manufacturer: Huawei
- Device model: LYA-AL10

![20230219104914](https://user-images.githubusercontent.com/98303833/219909665-2b88c04d-e748-4a0a-aaee-603edd4826c3.png)

**Comment by Catfriend1** [comment] 2023-03-09 21:35
Yes, me too. Many Syncthing(native) versions ago last year, the API events changed and they now provide more details on sync state, even if the affected remote device is not connected at the moment. This broke accounting in the wrapper. Syncing is still complete and functional, just the display of the percentage status accumulated from all event data the native sent to the wrapper is incorrect. When I've got time and motivation, I'll take a look.

**Comment by Catfriend1** [comment] 2023-03-09 21:35
Duplicate of #913

**Closed by Catfriend1** 2023-03-09 21:35 UTC
Labels: bug

**Comment by gbsix** [comment] 2023-03-16 14:24
> 

Just updated. Seems all right. Thanks!
