### ISSUE TITLE
syncthing crashes since v1.26.0.0

### ISSUE THREAD

**Issue by Sylonin** [Catfriend1/syncthing-android#1027] opened 2023-11-09 21:43 UTC
### Description of the issue
since the latest version syncthing crashes immediately after the app starts it
### Reproduction Steps
sometimes the app works fine but otherwise syncthing just starts crashing. sorry I can't provide more details :(

if I use the button to force the app to not run syncthing and then force start it it'll launch for ~2 second (status icon goes green, appnseems to connect to the syncthing spi) but then syncthing crashes after that 1 second :(
### Version Information
- App Version: 1.26.0.2
- Syncthing Version: Settings -> About -> syncthing version is blank
- Android Version: LineageOS 19.1
- Device manufacturer: OnePlus 
- Device model: 9 Pro

### Device platform info

```sh
[ro.product.ab_ota_partitions]: [abl,aop,bluetooth,boot,cpucp,devcfg,dsp,dtbo,engineering_cdt,featenabler,hyp,imagefv,keymaster,modem,multiimgoem,odm,oplus_sec,oplusstanvbk,product,qupfw,qweslicstore,shrm,splash,system,system_ext,tz,uefisecapp,vbmeta,vbmeta_system,vbmeta_vendor,vendor,vendor_boot,vendor_dlkm,xbl,xbl_config]
[ro.product.board]: [lahaina]
[ro.product.brand]: [OnePlus]
[ro.product.build.date]: [Mon Nov  6 04:02:33 UTC 2023]
[ro.product.build.date.utc]: [1699243353]
[ro.product.build.fingerprint]: [OnePlus/OnePlus9Pro_EEA/OnePlus9Pro:11/RKQ1.201105.002/2109102008:user/release-keys]
[ro.product.build.id]: [TQ3A.230901.001]
[ro.product.build.tags]: [release-keys]
[ro.product.build.type]: [userdebug]
[ro.product.build.version.incremental]: [cc8b4d8489]
[ro.product.build.version.release]: [13]
[ro.product.build.version.release_or_codename]: [13]
[ro.product.build.version.sdk]: [33]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [OnePlus9Pro]
[ro.product.first_api_level]: [30]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [OnePlus]
[ro.product.model]: [A0001]
[ro.product.name]: [OnePlus9Pro]
[ro.product.odm.brand]: [OnePlus]
[ro.product.odm.device]: [OnePlus9Pro]
[ro.product.odm.manufacturer]: [OnePlus]
[ro.product.odm.model]: [A0001]
[ro.product.odm.name]: [OnePlus9Pro]
[ro.product.product.brand]: [OnePlus]
[ro.product.product.device]: [OnePlus9Pro]
[ro.product.product.manufacturer]: [OnePlus]
[ro.product.product.model]: [A0001]
[ro.product.product.name]: [OnePlus9Pro]
[ro.product.system.brand]: [OnePlus]
[ro.product.system.device]: [OnePlus9Pro]
[ro.product.system.manufacturer]: [OnePlus]
[ro.product.system.model]: [A0001]
[ro.product.system.name]: [OnePlus9Pro]
[ro.product.system_ext.brand]: [OnePlus]
[ro.product.system_ext.device]: [OnePlus9Pro]
[ro.product.system_ext.manufacturer]: [OnePlus]
[ro.product.system_ext.model]: [A0001]
[ro.product.system_ext.name]: [OnePlus9Pro]
[ro.product.vendor.brand]: [OnePlus]
[ro.product.vendor.device]: [OnePlus9Pro]
[ro.product.vendor.manufacturer]: [OnePlus]
[ro.product.vendor.model]: [A0001]
[ro.product.vendor.name]: [OnePlus9Pro]
[ro.product.vendor_dlkm.brand]: [OnePlus]
[ro.product.vendor_dlkm.device]: [OnePlus9Pro]
[ro.product.vendor_dlkm.manufacturer]: [OnePlus]
[ro.product.vendor_dlkm.model]: [LE2125]
[ro.product.vendor_dlkm.name]: [OnePlus9Pro]
[ro.product.vndk.version]: [33]

```

### Android Log

https://src.dyne.link/-/snippets/3

**Comment by Catfriend1** [comment] 2023-11-09 22:47
Uh oh, this is not the wrapper but the SyncthingNative crashing. Please try to capture all line of SyncthingNative involved and contact upstream at forum.syncthing.net . Hopefully someone has an idea why the go code crashes. Does the app work fine after starting afresh (backup config first!)

**Comment by Sylonin** [comment] 2023-11-10 12:52
Ah ok, sorry, my bad

I'll contact upstream if the issue happens again - I cleared the app data and imported an export I made prior to clearing data and it seems stable now. :)

**Comment by phillipberndt** [comment] 2023-11-10 19:58
Had the same issue, and the same workaround seems to have helped for me. Thanks for sharing it!

For the record:

Syncthing native excited with code 2, no errors or panics in the log. I expect that it did panic and print the panic output to a different file descriptor than where other logs land!? Tried the log to file option but didn't manage to then find the logfile.

**Comment by blu3id** [comment] 2023-11-11 13:15
Also having the same issue. The workaround didn't work. I also can't get more useful logging beyond the native exit of code 2. 

However this is likely related to networking somewhere as I can reliably cause Syncthing to crash when connected to a particular network with mobile data on. It seems to start fine on other networks and if either mobile or wifi is disabled. It remains stable if started and then networks change. I suspect that upstream is unlikely to see this bug because Synching remains running constantly rather than being started on multiple different networks.

I will try to get useful logging and post bug report upstream.

**Comment by phillipberndt** [comment] 2023-11-12 12:47
The problem returned for me a day later, seems I just got lucky when testing before. Tried upstream Syncthing v1.26.0, and indeed it doesn't have the issue (so far).

**Comment by Catfriend1** [comment] 2023-11-12 13:25
> The problem returned for me a day later, seems I just got lucky when testing before. Tried upstream Syncthing v1.26.0, and indeed it doesn't have the issue (so far).

Do you mean the official Syncthing Android app ?

**Comment by phillipberndt** [comment] 2023-11-12 14:08
Right. With settings imported from an export from the fork.

**Comment by Catfriend1** [comment] 2023-11-12 14:16
I'll compare the build recipe for the native next dev session. Maybe go or ndk version differs?

**Comment by blu3id** [comment] 2023-11-12 23:13
As another data point: I have done what @phillipberndt did and imported export from fork into the official app and started it on while connected to the network that will reliable cause the fork to crash and it didn't. So while I still suspect this is networking related upstream/official build doesn't seem to be impacted so may well be build options related.

**Comment by blu3id** [comment] 2023-11-13 23:32
Managed to capture some logs but at first glance there doesn't seem to be much more detail than in @Sylonin original report. Sharing here in case it is useful: https://gist.github.com/blu3id/7a4dda385fa1b8fb37beb483ccbfd87b

**Comment by makew0rld** [comment] 2023-11-14 04:29
I'm also seeing pretty constant crashes, even after clearing app data and cache and re-importing.

**Comment by JanickGers85** [comment] 2023-11-16 00:38
Same here: the app crashes, the native one no, with the very same settings backup restored.

Here app logs
https://pastebin.com/TmWSacRe

**Comment by Catfriend1** [comment] 2023-11-16 18:15
To sum up: 
* it does not seem to be caused by the NDK or Go version in use (they were bumped and problem still exists)
* it does not affect all devices - mine work fine without a crash observed
* if some of you had a crash-free experience exporting the config to the official app, it is not a config issue triggering the crashes.

What about backing up your data, let it sync up to 100% in-sync state (if this is still possible?!) and then go to settings > ... > reset database? Does a full rescan and db rebuild help here to avoid the crash? At least worth a try, because if you "export and import to switch to official" your database is not imported (the official app doesn't have this feature in the code).

**Comment by Catfriend1** [comment] 2023-11-16 18:16
> Same here: the app crashes, the native one no, with the very same settings backup restored.
> 
> Edit: tried with v1.26.0.0 and latest v1.26.1.0, both version.
> 
> Here app logs https://pastebin.com/TmWSacRe

What is before those lines? I've heard from the upstream maintainers they are the most important ones to see where the crash came from. You can capture them by "adb logcat v" (Just google Android Debugging via USB).

```
01:22:44W/SyncthingNativeCode 	net/fd_unix.go:117 +0x2cc
01:22:44W/SyncthingNativeCode 
01:22:44W/SyncthingNativeCode goroutine 172 [select]:
01:22:44W/SyncthingNativeCode github.com/syncthing/syncthing/lib/dialer.dialTwicePreferFirst.func2()
01:22:44W/SyncthingNativeCode 	github.com/syncthing/syncthing/lib/dialer/public.go:162 +0xec
01:22:44W/SyncthingNativeCode created by github.com/syncthing/syncthing/lib/dialer.dialTwicePreferFirst in goroutine 194
01:22:44W/SyncthingNativeCode 	github.com/syncthing/syncthing/lib/dialer/public.go:161 +0x3c4
01:22:44W/SyncthingNativeCode 
01:22:44W/SyncthingNativeCode goroutine 171 [IO wait]:```

**Comment by Soundtoxin** [comment] 2023-11-17 03:30
Just hit this as well. Is there a way to downgrade to the previous version on F-Droid? I'm hesitant to uninstall and then install an old version since it may discard settings. I see the previous versions listed but don't see a way to install. I exported my config just in case, but only from the latest broken version, so who knows if it's even good.

**Comment by Catfriend1** [comment] 2023-11-18 20:21
I still don't know where the crash exactly happens in the native code to forward the ticket to the go code devs of SyncthingNative. What a tricky case, it doesn't crash on my phone nor emulator.

There was a different problem those days when Android auto-revoked the notification permission on the app. This has been fixed in the latest 1.26.1.0 release where the app politely asks again for the permission.
.

**Comment by libreinator** [comment] 2023-11-19 05:51
I have the same issue (similar logs) and I found it does not crash when the other devices are offline at the time syncthing-fork on android starts.

This is what I have tried so far:
- **start syncthing on desktop, then start syncthing-fork on android**: syncthing-fork crashes (I believe the crash occurs as soon as both instances connect with each other)
- **stop syncthing on desktop, start syncthing-fork on android, then start syncthing on desktop**: syncthing-fork does not crash and the files sync without any problem

I'm on Syncthing-Fork v1.26.0.2 with syncthing v1.26.0 on android (installed from f-droid) and syncthing v1.26.1 on arch linux.

**Comment by Catfriend1** [comment] 2023-11-19 07:27
This is an interesting observation. My setup connects Android with an always on server. Should it then crash when turning on the app? From reading your post yes, but indeed, it does not on my phone.

**Comment by libreinator** [comment] 2023-11-19 09:10
> This is an interesting observation. My setup connects Android with an always on server. Should it then crash when turning on the app? From reading your post yes, but indeed, it does not on my phone.

I just found out syncthing-fork does not crash when the desktop and phone are connected to different networks and they communicate using relays. Maybe your server is not on the local network and you're connected using relays or some other way?

**Comment by Catfriend1** [comment] 2023-11-19 09:24
@libreinator I have turned off all discovery methods on my phone (4 disabled check boxes). Then I configured my servers IP in the device entry (Android). The server sits on the same network, connected via Lan cable, my phone uses Wifi.

**Comment by Catfriend1** [comment] 2023-11-19 09:33
What about doing adb logcat v > logfile.log and grabbing the whole crash report from the beginning?

**Comment by codemole** [comment] 2023-11-19 09:38
FWIW, I can confirm @libreinator's observation about importance of instance start order. Some additional notes:
- the connection type for me is `TCP WAN`, so I'm guessing no relay is involved and thus it's not a requirement.
- syncthing-fork connects to two other instances for me. All have distinct syncthing versions. I only need to have the v1.24.0 (FreeBSD) instance shut down for the ST-Fork to start correctly. The other instance is v1.25.0 (Linux) and it's running state doesn't affect the Android app (v1.26.0.2)

**Comment by Catfriend1** [comment] 2023-11-19 09:47
@codemole could you please try to upgrade the other nodes to v1.26.1 ? Since 1.25+ upstream has added a multiple connections handling to Syncthing. Maybe there' s some version incompatibility bug triggering the crash?

My nodes all have 1.26+.

**Comment by codemole** [comment] 2023-11-19 09:57
@Catfriend1, I can update the Linux client, it didn't seem to change anything. FreeBSD is more complicated, since stable only has 1.24 in their repos. For the latest version I think I'd need to build syncthing myself. Not a FreeBSD pro though, might be some other way.

Another observation, if I put the shared folder on `Pause`, the v1.24 instance can remain running and ST-Fork will start just fine.

**Comment by Catfriend1** [comment] 2023-11-19 10:00
Just as a sidenote: I think we could benefit from taking this issue to the Syncthing forum. My feeling says this is Syncthing(native) related and has nothing to do with the wrapper I'm maintaining here. Plus, the crash logs above are also native parts of Syncthing spitting them out.

**Closed by Catfriend1** 2023-11-19 10:00 UTC
Labels: investigation

**Comment by codemole** [comment] 2023-11-19 10:11
@Catfriend1, fair enough. What would be the best place to report this to syncthing guys? Just straight into the forum or [github](https://github.com/syncthing/syncthing/issues) is better?

**Comment by Catfriend1** [comment] 2023-11-19 10:13
Please capture the full native crash log and show it on the forum together with the pointer to the different versions.

**Comment by codemole** [comment] 2023-11-19 10:29
As a final note, I've tried syncing the v1.24 instance to v1.26.1 (Linux) and v1.26.1 (Windows) and neither to crashes upon start. The Android version seems to be the only one affected.

**Comment by Catfriend1** [comment] 2023-11-19 10:34
Very strange, but not my code :(

**Comment by blu3id** [comment] 2023-11-19 12:08
Forum post: https://forum.syncthing.net/t/syncthing-1-26-crashing-on-android-in-syncthing-fork/21115

Also for reference I have now managed to capture the Logcat output of the crash that has slightly more detail: https://gist.github.com/blu3id/cddab7352ce6586e3ba999e346795206

**Comment by Catfriend1** [comment] 2023-11-19 12:15
@blu3id The log is perfect ! That's what we need so upstream devs can tell us where it crashes and hopefully give advice what do to next. It seems Syncthing's indexHandler has a Problem.

**Comment by Catfriend1** [comment] 2023-11-21 16:22
Yeah, upstream did a fix on that. Will need to wait for 1.27 to be released including the fix.

**Comment by Catfriend1** [comment] 2023-11-22 00:17
Please report back if https://github.com/Catfriend1/syncthing-android/releases/download/v1.27.0.0/com.github.catfriend1.syncthingandroid_github_v1.27.0.0_7302b491.apk works without crashing. It contains the latest upstream commits from https://github.com/syncthing/syncthing/pull/9235 .

**Comment by Soundtoxin** [comment] 2024-01-10 17:03
I still get crashes / syncthing going to sleep pretty often on 1.27.0.1 but occasionally it must manage to sync because I do get pictures I took appearing on my PC most of the time.

**Comment by Catfriend1** [comment] 2024-01-13 11:03
Try the latest 1.27.2.1 version, please.
