### ISSUE TITLE
FC after latest beta update

### ISSUE THREAD

**Issue by Th3Shap3r** [Catfriend1/syncthing-android#536] opened 2019-11-07 08:00 UTC
### Version Information
    App Version: 1.3.1.1 (Beta)
    Android Version: Android 10 / AOSIP Derpquest
    Device manufacturer: OnePlus
    Device model: OnePlus 5T

**Comment by Th3Shap3r** [comment] 2019-11-07 08:54
Updated to 1.3.1.3 (Beta) still getting fc
###Log : https://del.dog/geyivamije

**Comment by Catfriend1** [comment] 2019-11-07 09:32
Thanks for telling me about the problem with the recent release.
I'll Investigate that later when at a PC.
In the meantime:
Could you or someone else reading this please download the two release apk's from github and report back if they work on devices where the gplay downloaded one did not work?
I suspect the app code is correct and doesn't have a bug causing this - but the gplay release was "advised" by google to use app bundles instead of the classic apk release. The logs I received clearly state that the bundled native .so file isn't correctly shipped by Google Play onto your devices - you then ended up having a wrapper but no SyncthingNative (functional core of upstream Syncthing). That's why it crashes from Android's perspective.

General advice:
- Do NOT reset app data or cache from Android settings
- Stay calm and wait for the next update. 
- You would loose your syncthing device ID, config and maybe some sync folder data if you uninstall the app.
- If you urgently need to sync something, grab the Github release from here and install it on your phone with "adb install -r ....apk". You then have a second instance with a new device ID available intermediately.

**Comment by cthu1hoo** [comment] 2019-11-07 09:36
Just tried and _gplay APK from github releases page works properly.

**Comment by Th3Shap3r** [comment] 2019-11-07 09:42
@Catfriend1 @cthu1hoo Tried _gplay apk from and it's working fine.

**Comment by Catfriend1** [comment] 2019-11-07 09:47
Thanks @cthu1hoo ! That's what I expected as I can only test apk's on my devices before release. The app bundle was totally new to me.

So here's what I'll do to fix it:
- Google put the update live, so I'll install it on my test devices through play store as its now available for download on that way.
- If Google App Bundling is "defective", I'll try to put up a fixed one or definiton? (Manifest problem?) to fix it.
- If that doesn't work, let's try to rerelease on the old apk upload way to gplay (google maybe will block this as they want their app bundle I recall....?)
- last resort: I'll reach out to Gplay dev support and ask them whats wrong with the release.

Intermediate solution for people stuck: You can *maybe* update via the GPlay APK posted here on my release page. 

I currently have no clue why the app bundle doesn't ship the native correctly for arm, arm64 and so on. Google made this feature to reduce app download size and reported fine on 11 to 12 mbyte per download yesterday which is near my expectations for wrapper and syncthingnative. (The apk contained all three natives before from which you only used one corresponding to your phone architecture).

Anyone out there who can give me advise what I did wrong with app bundling? I put myanifest and build script on the repo in case you want to have a look at it.

**Comment by Catfriend1** [comment] 2019-11-07 09:48
@Th3Shap3r Were you able to upgrade an existing gplay installation by using the github apk without config or data loss?

**Comment by cthu1hoo** [comment] 2019-11-07 09:49
Why even use app bundles? I've never bothered personally because making an APK and using it internally for testing and then publishing it to play store seems a lot easier than bothering with whatever proprietary play-store-only thing app bundles are.

>Were you able to upgrade an existing gplay installation
That's exactly what I did. Installed _gplay apk on top of borked play store version and it just worked with my existing setup.

**Comment by Th3Shap3r** [comment] 2019-11-07 09:52
@Catfriend1 Yes Just installed on top of PS version and it's working fine.

**Comment by Catfriend1** [comment] 2019-11-07 09:53
Yeah it's proprietary google play stuff - I should have distrusted this before... :-(
I just tried it to keep low system app storage in mind because some phones in the family and friends area offer very little app storage and I'd liked to help here. Sorry, it was a good intention with a bad outcome.

**Comment by Catfriend1** [comment] 2019-11-07 10:00
Just for completeness: Even a fresh install doesn't work - that's disappointing from the google app bundle feature. Confirmed the gplay store doesn't stream the integral part of the app. Will be fixed soon...

**Comment by Catfriend1** [comment] 2019-11-07 10:47
Here's a SO with the same problem : 
https://stackoverflow.com/questions/51092745/android-app-bundle-apk-doesnt-include-required-native-library

Should be fix-able by the gradle file...

**Comment by Catfriend1** [comment] 2019-11-07 10:51
Or this one, with uncompressed natives:
https://stackoverflow.com/questions/56551036/native-libraries-not-found-in-applicationinfo-nativelibrarydir-when-building-app

Can anyone please look into the /data/app/... path if the libsyncthing.so file got extracted or if it missing when Syncthing does not start?

**Comment by Catfriend1** [comment] 2019-11-07 16:48
This is pretty weird because Android x86 VM with Android 8.0 works fine downloading v1.3.1.3 from GPlay BETA channel. I'm setting up a test device with GPlay Store to be able to check.
![image](https://user-images.githubusercontent.com/16361913/68409090-c9bbe080-0186-11ea-9687-7ac903a3ab18.png)

**Comment by Catfriend1** [comment] 2019-11-07 17:24
I've made an AAB (Android Bundle) extractor script to further analyse where the problem came from.

**Comment by Catfriend1** [comment] 2019-11-07 17:28
Took "standalone-x86_xxxhdpi.apk" (~ 13 MByte) from the extraction and installed it to the x86 emulator running Android 9 -- works.

**Comment by Catfriend1** [comment] 2019-11-07 17:35
Took "standalone-x86_xxxhdpi.apk" (~ 13 MByte) from the extraction and installed it to the x86 emulator running Android 10 -- works.

Why does the "Google Play Cloud" distribute the wrong APK when someone taps download on a real device? Why doesn't it happen to my unofficial emulator running GPlay Store where Syncthing-Fork works okay?

**Comment by Catfriend1** [comment] 2019-11-07 18:28
Ok, got the PR so far the error is caught and shown on UI if it happens.
I now know, it only happens if the compressed variant (base-master, base-de, base-armv8) of the splits is installed to the real device. This can be reproduced by connecting an Android phone to the PC and ...

- running convert_bundle_to_apks.cmd
- running install_apks_to_device.cmd

This simulates the whole process of releasing the built Android Bundle to GPlay and downloading via Play Store "via" USB cable and fastens my analysis of the problem enormously.

**Closed** 2019-11-07 18:35 UTC
Labels: urgent

**Comment by Catfriend1** [comment] 2019-11-07 18:39
The fix will be part of an upcoming release. When it arrives, is up to Google. During the last releases, they took between hours and almost 7 days to review the update submission before approving it. Let's hope it will go through quickly.

**Comment by Catfriend1** [comment] 2019-11-07 18:40
Building release ...

**Comment by Catfriend1** [comment] 2019-11-07 18:43
Build SUCCESSFUL. Uploading release to GitHub and GPlay ...

```
[INFO] Checking if SyncthingNative was built before starting this script ...
[INFO] Let's prepare a new "Syncthing-Fork" GPlay release.
[INFO] Checking release prerequisites ...
Enter signing password: 
[INFO] Running lint before building ...
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
[INFO] Building Android APK variant "debug" ...
    android:versionCode="1030104"
    android:versionName="1.3.1.4" >
[INFO] Building Android APK variant "release" ...
    android:versionCode="1030104"
    android:versionName="1.3.1.4" >
[INFO] Building Android BUNDLE variant "release" ...
[INFO] Running OPTIONAL post build script ...

[INFO] Built debug APK for GitHub (signing certificate hash: 2ScaPj41giu4vFh+Y7Q0GJTqwbA=)
[INFO] Built release APK for Google Play (signing certificate hash: dQAnHXvlh80yJgrQUCo6LAg4294=)
[INFO] Deleting unsupported play translations ...
```

**Comment by Catfriend1** [comment] 2019-11-07 18:49
![image](https://user-images.githubusercontent.com/16361913/68417975-a5b4cb00-0197-11ea-887c-7e670ec4367e.png)

**Comment by Catfriend1** [comment] 2019-11-07 22:18
I prepared my phone with the stuck state v1.3.1.3 and some minutes ago gplay store updated the app to v1.3.1.4. So far, everything is working again. :-)

**Comment by rhamzeh** [comment] 2019-11-07 22:19
I just got the update and it's working :man_dancing: 

Thanks @Catfriend1 for the awesome work!

**Comment by DrSchnagels** [comment] 2019-11-07 22:31
Got the update after force closing the Play Store.
Works again very good!!! :)))))
Thanks a lot!!
