### ISSUE TITLE
Syncthing-Fork called "Sync. Camera" on F-Droid

### ISSUE THREAD

**Issue by tomasz1986** [Catfriend1/syncthing-android#606] opened 2020-01-18 04:38 UTC
# Description of the issue

F-Droid seems to pick up "Sync. Camera" as a name of the whole application. I do not think this is intended, is it?

Website:

![image](https://user-images.githubusercontent.com/5626656/72658677-948a0500-39f7-11ea-8df4-161d8169e073.png)

F-Droid app store:

![image](https://user-images.githubusercontent.com/5626656/72658667-699fb100-39f7-11ea-9c51-b0ae6f645efe.png)

On the application installation screen, it is still Syncthing-Fork.

![image](https://user-images.githubusercontent.com/5626656/72658669-80de9e80-39f7-11ea-8f3c-8e036893df0f.png)

**Comment by Catfriend1** [comment] 2020-01-18 09:44
Hmm... My fdroid client shows:
![Screenshot_2020-01-18-10-43-52-996_org fdroid fdroid](https://user-images.githubusercontent.com/16361913/72661844-83cd9500-39df-11ea-9e78-c356a88d0ce7.jpg)

**Comment by Catfriend1** [comment] 2020-01-18 09:46
They parse the app manifest and somehow pickup the secondary launch activity instrad of the one marked as primary. Feel free to report it to fdroidserver repo at gitlab. I cannot solve this from my side.

**Comment by Catfriend1** [comment] 2020-01-18 13:29
Duplicate of: #https://github.com/Catfriend1/syncthing-android/issues/519

**Comment by tomasz1986** [comment] 2020-01-19 07:55
https://gitlab.com/fdroid/fdroiddata/issues/1924

**Comment by Catfriend1** [comment] 2020-01-19 09:29
Thanks for your help

**Comment by forrestguice** [comment] 2020-01-25 04:50
This happened to my app like 10 months ago after I added a second launcher activity. As you've discovered, the name is taken from the wrong activity when there is more than one activity with a launch `intent-filter`.

I found a work around by adding an `activity-alias` that pointed to my second activity, and moving the launch intent-filter into that.

**Comment by Catfriend1** [comment] 2020-01-25 08:17
Hi, could you please post the relevant manifest xml part so I could look at it?

**Comment by forrestguice** [comment] 2020-01-25 08:58
Sure. I've copied the relevant parts of my [manifest](https://github.com/forrestguice/SuntimesWidget/blob/master/app/src/main/AndroidManifest.xml) into this [gist](https://gist.github.com/forrestguice/32803ed74cffc730b7890c1aef34aaa3).

**Comment by Catfriend1** [comment] 2020-02-08 18:25
@forrestguice Thank you. Do I get this right that I just have to add the following part "alias" for my main activity (which should be the default and is NOT the camera launcher)?

Toggling on off the secondary (camera) launcher activity already works in Syncthing-Fork.

```
<activity-alias
            android:name=".alarmclock.ui.AlarmClockActivityLauncher"
            android:targetActivity=".alarmclock.ui.AlarmClockActivity"
            android:enabled="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <meta-data android:name="android.app.shortcuts"
                android:resource="@xml/shortcuts_alarms" />

        </activity-alias>
```

**Comment by forrestguice** [comment] 2020-02-08 20:12
Hrm, I think the other way around. Leave your main activity alone. Add an alias pointing to the camera launcher that contains the intent-filter

```
<activity-alias
            android:name=".activities.PhotoShootActivityAliasOrWhateverYouWantToCallIt"
            android:targetActivity=".activities.PhotoShootActivity"
            android:enabled="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

</activity-alias>
```
and remove the intent-filter from the camera activity itself
 ```
<activity
                android:name=".activities.PhotoShootActivity"
                android:icon="@mipmap/ic_launcher_photoshoot"
                android:label="@string/photo_shoot_launcher_title"
                android:launchMode="singleInstance">
</activity>
```

F-Droid will only discover the main activity (it overlooks the alias) and should take the right name.

**Comment by Catfriend1** [comment] 2020-03-14 18:07
Seems to be ok "by its own" now.
https://f-droid.org/de/packages/com.github.catfriend1.syncthingandroid/
https://f-droid.org/en/packages/com.github.catfriend1.syncthingandroid/

and on the f-droid app it is okay on my test android, too.

**Closed by Catfriend1** 2020-03-14 18:07 UTC
Labels: publishing
