### ISSUE TITLE
Can't bypass battery optimization on Android tv 

### ISSUE THREAD

**Issue by the-mentor** [Catfriend1/syncthing-android#210] opened 2019-01-07 18:21 UTC
I'm running syncthing-fork 1.0.0.1 o  the nvidia shield tv 2017 running android tv 8.0. 
When going through the welcome wizard I'm asked to setup the battery optimization but unable to proceed my guess is that android tv is an always connected device so it doesn't have the battery optimization part of android is there an option to add a skip for this check on Android tv devices? 

Thanks. 
-DM

**Comment by Catfriend1** [comment] 2019-01-07 18:50
This was already "fixed" in  v1.0.0.2 . Please upgrade your installation. As this is an Android restriction causing the problem, you'll also need the wiki article from user @o-l-a-v to solve to the problem, found here: https://github.com/Catfriend1/syncthing-android/wiki/Android-TV-preparations
Duplicate of: https://github.com/Catfriend1/syncthing-android/issues/192
More: https://forums.geforce.com/default/topic/1092750
GitHub release: https://github.com/Catfriend1/syncthing-android/releases/download/v1.0.0.2/com.github.catfriend1.syncthingandroid_v1.0.0.2_ae2e1874.apk

**Closed by Catfriend1** 2019-01-07 18:50 UTC
