### ISSUE TITLE
[Feature Request] Make Syncthing-Fork available through Google Play Store for Android TV

### ISSUE THREAD

**Issue by o-l-a-v** [Catfriend1/syncthing-android#194] opened 2019-01-04 19:25 UTC
Syncthing-Fork is currently not available through Google Play Store for Android TV, while Synthing-Android is.
Would be very nice if we could install and update Syncthing-Fork on Android TV using Google Play Store for Android TV.

**Comment by Catfriend1** [comment] 2019-01-04 19:36
Hey, it's just two days on the play store, come on. Just kidding :). I'll check how to submit it for TV's when having some time for that. GPlay needs a special submission for that as I recall...

**Comment by o-l-a-v** [comment] 2019-01-04 19:40
Great, thanks :)
No hurry, just thought creating a issue while I had it on my mind would be smart.

**Comment by Catfriend1** [comment] 2019-01-04 19:42
Ahhhh it's here:
![image](https://user-images.githubusercontent.com/16361913/50707448-28916480-1061-11e9-885b-dd22350dd95e.png)

I've submitted the enquiry to offer this app on Android TV's to Google Play. It's now up to them if they accept it like the upstream app.
![image](https://user-images.githubusercontent.com/16361913/50707494-4fe83180-1061-11e9-9b06-76678cf953ef.png)

**Comment by Catfriend1** [comment] 2019-01-04 21:01
According to google notification, it should be done.
![image](https://user-images.githubusercontent.com/16361913/50710761-33052b80-106c-11e9-9585-24a56c57aba7.png)
Can you please check on your TV If it's visibile on the play store? (no install required)

**Comment by o-l-a-v** [comment] 2019-01-04 23:01
Will check tomorrow, thanks.

**Comment by Catfriend1** [comment] 2019-01-05 00:55
Google rejected it:
Reason: "No full-size app banner"

**Comment by Catfriend1** [comment] 2019-01-05 09:11
Ok thanks for checking this out. I'll come back to this shortly

**Comment by Catfriend1** [comment] 2019-01-05 09:37
Looking at the resources folder, it hasn't got the banner in the right folder (but that also applies to the upstream app which I think got approved before the rules came to google play?!).
The banner lies in res/drawable-nodpi . AndroidManifest.xml is okay.

Source: https://developer.android.com/training/tv/start/start#banner
> The banner should be an xhdpi resource with a size of 320 x 180 px. Text must be included in the image. If your app is available in more than one language, you must provide separate versions of the banner with text for each supported language.

**Comment by Catfriend1** [comment] 2019-01-06 08:55
Oh my, the current release 1.0.0.2 is still rejected by gplay but I didn't get a new report what's wrong.

**Comment by o-l-a-v** [comment] 2019-01-06 09:58
Might be due to either of the following:
- Grant permission to disable Doze for Syncthing-Fork does not work on Android TV Oreo, and thus should not be run if running on Android TV
- It's not possible to setup Syncthing-Fork, or Syncthing-Amdroid for that matter, without using a PC mouse. Aka not fully Android TV compatible.

**Comment by Catfriend1** [comment] 2019-01-06 11:32
In really thought both were done. The doze api isn't called any longer where the dialog was missing as it's detected from code. The second needs to be checked again on a TV. Thought we have key support already.

**Comment by Catfriend1** [comment] 2019-01-07 06:31
There are even more problems reported on the related threads:
https://github.com/syncthing/syncthing-android/issues/717
https://github.com/syncthing/syncthing-android/issues/486

**Comment by Catfriend1** [comment] 2019-01-09 19:42
Just reading through the android dev docs... ( https://developer.android.com/training/tv/start/controllers )
There is a part that mentions an activity is getting restarted? recreated? when the dpad controller goes to sleep. @o-l-a-v Can you please tell me if you observe that behaviour in Syncthing or are the disconnects totally random-looking?

**Comment by o-l-a-v** [comment] 2019-01-10 11:52
What disconnects? Syncthing "client" to Syncthing "server", or dbad controller to Shield?
I'm away for some days, will check when I'm home again on Sunday.

**Comment by Catfriend1** [comment] 2019-01-10 16:22
Both, one couls trigger the other.

**Comment by Catfriend1** [comment] 2019-01-13 14:58
@o-l-a-v I've made a draft to comply with Android's TV app rules on MainActivity (main screen). It's at #222 if you'd like to have a look. The problem is that the Toolbar/ActionBar widgets don't work on Android TV's android OS. This is also stated in the Android developer docs. So what we'd need to finish this PR is a complete reimplemenation of the toolbar and action buttons.
Too much work for now, honestly. But I'll leave it open in case you or some one else likes to continue it and help in development.

**Comment by o-l-a-v** [comment] 2019-01-13 19:13
@Catfriend1 I'tried connecting, disconnectong the nVidia game pad, is see no disconnects from the server that feeds Syncthing-Fork. No disconnect when putting the Shield to sleep using the nVidia game pad either. Is this what you needed?

**Comment by Catfriend1** [comment] 2019-01-13 19:47
Yes, thanks for testing this out.

**Comment by Catfriend1** [comment] 2019-01-16 00:48
@o-l-a-v  Wanna try and provide feedback to the BETA? https://drive.google.com/open?id=1XnooXSFAsT5rf-qyxkO2_pZ0XywYcdHZ

**Comment by Catfriend1** [comment] 2019-01-16 08:22
Woah go--gle is so getting on my nerves. Everything worked during my tests now they complain again:
> App links to or depends on web browser
Your app relies on presentation of  web content. Android TV does not support any web browsing content. Please refer to our documentation for details.For example, your app links to web content in the report issues page.

**Comment by o-l-a-v** [comment] 2019-01-16 12:10
> Woah go--gle is so getting on my nerves. Everything worked during my tests now they complain again:
> 
> > App links to or depends on web browser
> > Your app relies on presentation of  web content. Android TV does not support any web browsing content. Please refer to our documentation for details.For example, your app links to web content in the report issues page.

Damn, their picky. 
Their previous routines for testing couldn't have been much to speak of, lots on noncompliant apps in the Google Play Store for Android TV. Syncthing-Android for instance.
I bet they had the floodgate open until they had a minimum number of apps.

**Comment by o-l-a-v** [comment] 2019-01-16 20:47
@Catfriend1 
Regarding the beta I'm facing some problems:
* I get to the Welcome screen every time I open the app, even after initialization and after restoring a backup from previous installation. Tried to force close the app aswell, same thing.
* The layout does not seem to scale well, some buttons are way to close to the border of the TV. Some icons with text almost touches each other. See pictures.

**Comment by Catfriend1** [comment] 2019-01-19 15:36
@o-l-a-v Thanks for your detailed feedback. I'm getting to it when the "Google stuff" for the app to be accepted on TV is done. Currently, I'm releasing the BETA 1.0.0.14 on GPlay beta channel.

>I get to the Welcome screen every time I open the app, even after initialization and after restoring a backup from previous installation. Tried to force close the app aswell, same thing.

I tested this on a virtual TV (AVD): The welcome screen repeats only until adb "ignore battery" was fired. Is that the culprit here?

**Comment by Catfriend1** [comment] 2019-01-19 16:14
> Hovering the Add device icon when on device tab, it gets black. But not the same for Status (Settings) and Folders (Add folder).
The folder icon is fixed since 1.0.0.14. For the settings icon, I've registered ticket #243.
![image](https://user-images.githubusercontent.com/16361913/51429306-afbc0c00-1c0d-11e9-84a3-a9767bc89084.png)

**Comment by Catfriend1** [comment] 2019-01-19 16:15
> Some icons inside the hamburger menu are totally black, others are dark gray. 
I must admit I'm not a good designer. So if you know someone or like to help me I'd appreciate a submission of new drawables.

**Comment by Catfriend1** [comment] 2019-01-19 16:17
![image](https://user-images.githubusercontent.com/16361913/51429324-f4e03e00-1c0d-11e9-9e76-80d71fd4ba74.png)
> It looks like Settings inside the hamburger menu is always selected/ hovered. Visually.

This isn't the case on my "test TV":
![image](https://user-images.githubusercontent.com/16361913/51429336-12ada300-1c0e-11e9-8c9c-575b2cf07546.png)

Maybe it's specific to NVIDIA Shield TV?

**Comment by Catfriend1** [comment] 2019-01-20 14:43
@o-l-a-v I've put up a new release improving UI flows according to your feedback. See https://github.com/Catfriend1/syncthing-android/releases/tag/v1.0.0.15 or GPlay Beta channel.

**Comment by Catfriend1** [comment] 2019-01-20 14:47
I'm closing this as it gets very long and hard to read. Feel free to open a new issue if you discover more UI glitches or problems related to Android TV. Issue subject should start with "Android TV:" in case.

**Closed by Catfriend1** 2019-01-20 14:47 UTC
Labels: enhancement, pr-welcome

**Comment by Catfriend1** [comment] 2019-01-21 21:02
Again , a rejection from gplay:
> APK:1000016 Missing dpad functionality

I've tested this so much on the emulator. Did you notice any dpad functionality missing in 1.0.0.16?

**Comment by o-l-a-v** [comment] 2019-01-21 23:01
I'll have better time to test tomorrow, will let you know if I find any missing dpad navigation functionality.

**Comment by Catfriend1** [comment] 2019-01-22 07:47
Google says it's this:
![image](https://user-images.githubusercontent.com/16361913/51519821-55e05f80-1e22-11e9-9839-295b3a5052cf.png)
I don't feel like removing it is a good idea?!? Any suggestions?

**Comment by o-l-a-v** [comment] 2019-01-25 06:47
You did it @Catfriend1! Just got a update to Syncthing-Fork through Google Play for Android TV!

Your work in making Synthing-Fork compatible with Android TV is much appreciated, thank you.

**Comment by Catfriend1** [comment] 2019-01-25 07:15
So you got version 1.0.0.18 now from gplay beta? Thanks for helping me through this. :-)

**Comment by o-l-a-v** [comment] 2019-01-25 07:17
Yes, 1.0.0.18.

No problem. :)
Will let you know if I find any more bugs or feature requests when navigating on ATV, when I got time.
