### ISSUE TITLE
feature request : untrusted devices + receive/send encrypted

### ISSUE THREAD

**Issue by IPv777** [Catfriend1/syncthing-android#840] opened 2021-08-25 04:52 UTC
### Description of the issue
Hello, I would like a support of the new feature "untrusted devices" 🙃

Thanks 🥰

**Comment by Catfriend1** [comment] 2021-08-25 08:51
Hi,

I'd like to have this, too. Feel free to take a look at https://github.com/Catfriend1/syncthing-android/pull/725 where the UI implementation already started.

**Comment by Catfriend1** [comment] 2021-09-12 09:10
Duplicate of #724

**Closed by Catfriend1** 2021-09-12 09:10 UTC
Labels: enhancement
